
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author santi
 */
public class jfrmCajas extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(jfrmCajas.class.getName());

    /**
     * Creates new form jfrmCajas
     */
    public jfrmCajas() {
        initComponents();
        this.setTitle("Cajas de text");
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jbtVD = new javax.swing.JButton();
        jbtCD = new javax.swing.JButton();
        jbtRD = new javax.swing.JButton();
        jbtP1 = new javax.swing.JButton();
        jbtP2 = new javax.swing.JButton();

        jPanel1.setForeground(new java.awt.Color(0, 102, 204));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(0, 102, 255));

        jLabel1.setBackground(new java.awt.Color(51, 255, 204));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel1.setText("Cajas de dialogo");

        jbtVD.setBackground(new java.awt.Color(51, 204, 255));
        jbtVD.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jbtVD.setText("Visualizar Datos");
        jbtVD.addActionListener(this::jbtVDActionPerformed);

        jbtCD.setBackground(new java.awt.Color(51, 204, 255));
        jbtCD.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jbtCD.setText("Confirmar Datos");
        jbtCD.addActionListener(this::jbtCDActionPerformed);

        jbtRD.setBackground(new java.awt.Color(51, 204, 255));
        jbtRD.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jbtRD.setText("Requerir Datos");
        jbtRD.addActionListener(this::jbtRDActionPerformed);

        jbtP1.setBackground(new java.awt.Color(51, 204, 255));
        jbtP1.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jbtP1.setText("Problema 1");
        jbtP1.addActionListener(this::jbtP1ActionPerformed);

        jbtP2.setBackground(new java.awt.Color(51, 204, 255));
        jbtP2.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jbtP2.setText("Problema 2");
        jbtP2.addActionListener(this::jbtP2ActionPerformed);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jbtCD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbtVD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbtRD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbtP1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbtP2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(111, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbtVD)
                .addGap(18, 18, 18)
                .addComponent(jbtCD)
                .addGap(18, 18, 18)
                .addComponent(jbtRD)
                .addGap(18, 18, 18)
                .addComponent(jbtP1)
                .addGap(18, 18, 18)
                .addComponent(jbtP2)
                .addGap(0, 34, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtVDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtVDActionPerformed
        JOptionPane.showMessageDialog(null,"La palabra no es correcta","Error",JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_jbtVDActionPerformed

    private void jbtCDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtCDActionPerformed
        JOptionPane.showConfirmDialog(null, "Deseas Continuar");
    }//GEN-LAST:event_jbtCDActionPerformed

    private void jbtRDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtRDActionPerformed
        String clave = JOptionPane.showInputDialog("La palabra de paso:");
    }//GEN-LAST:event_jbtRDActionPerformed

    private void jbtP1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtP1ActionPerformed
        String clave;

        
            clave = JOptionPane.showInputDialog(null, "Ingrese con su nombre:");

            if (clave == null) {
                
            }

            if (clave.equals("Santiago Ortiz")) {
                JOptionPane.showConfirmDialog(null, "Ingreso correctamente ¿Deseas Continuar?");
            } else {
                JOptionPane.showMessageDialog(null, "Vuelva a intentarlo","Error",JOptionPane.ERROR_MESSAGE);
            }

        
        

    }//GEN-LAST:event_jbtP1ActionPerformed

    private void jbtP2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtP2ActionPerformed
        Object[] opciones ={"Si, mucho","Mas o menos","No, me dan miedo"};
        int n=JOptionPane.showOptionDialog(this,"Le gusta las peliculas de terror","Opciones",JOptionPane.YES_OPTION,JOptionPane.QUESTION_MESSAGE,null,opciones,opciones[2]);
    }//GEN-LAST:event_jbtP2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new jfrmCajas().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton jbtCD;
    private javax.swing.JButton jbtP1;
    private javax.swing.JButton jbtP2;
    private javax.swing.JButton jbtRD;
    private javax.swing.JButton jbtVD;
    // End of variables declaration//GEN-END:variables
}
